"""add annual reports and event registrations

Revision ID: 86e05ce78d90
Revises: 37b0022d09ac
Create Date: 2026-07-07 22:28:47.135020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e05ce78d90'
down_revision: Union[str, None] = '37b0022d09ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annual_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('financial_year', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annual_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annual_reports_financial_year'), ['financial_year'], unique=False)

    op.create_table('event_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('custom_responses', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_registrations_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_registrations_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_fields', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('form_fields')

    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_registrations_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_registrations_event_id'))

    op.drop_table('event_registrations')
    with op.batch_alter_table('annual_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annual_reports_financial_year'))

    op.drop_table('annual_reports')
    # ### end Alembic commands ###
