"""add member portal fields and announcements

Revision ID: b5e1f3d56f1e
Revises: 91a20f772e01
Create Date: 2026-07-13 00:37:16.190228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5e1f3d56f1e'
down_revision: Union[str, None] = '91a20f772e01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('member_announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_announcements_display_order'), ['display_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_announcements_is_published'), ['is_published'], unique=False)

    with op.batch_alter_table('member_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sa.String(length=100), nullable=False, server_default='General'))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=False, server_default='Ahmedabad'))
        batch_op.add_column(sa.Column('occupation', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('profile_completed', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.create_index(batch_op.f('ix_member_profiles_surname'), ['surname'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_profiles_surname'))
        batch_op.drop_column('profile_completed')
        batch_op.drop_column('occupation')
        batch_op.drop_column('city')
        batch_op.drop_column('surname')

    with op.batch_alter_table('member_announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_announcements_is_published'))
        batch_op.drop_index(batch_op.f('ix_member_announcements_display_order'))

    op.drop_table('member_announcements')
    # ### end Alembic commands ###
